server:
  port: 9191

spring:
  main:
    allow-circular-references: true

  application:
    name: simplecaptcha

  datasource:
    url: jdbc:postgresql://localhost:5432/simple_captcha_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

###########
# Captcha #
###########
captcha:
  width: 300
  height: 40
  duration:
    seconde: 300
purge:
  expired-captcha:
    seconde: 60